### ISSUE TITLE
Link request

### ISSUE THREAD

**Issue by kyzmitch** [sergeyleschev/ios-dev-skills#1]
could you give the link to the original repo? Can't find it on github right away

**Comment by sergeyleschev** [comment]
All `tasks` have been described by me, so it's unlikely you'll find them anywhere else but in this repository. I've spent a long time gathering employee evaluation structures from `various sources` and tailored them to suit the specific needs of my department. You can find the my final structure in this repository. Whether it suits you or not, it's up to you to decide :)
